spring:
  application:
    name: transfer-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        "[spring.json.add.type.headers]": false
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      accountService:
        ignore-exceptions:
          - com.multimatics.bankflow.transfer.integration.account.RemoteAccountNotFoundException
          - com.multimatics.bankflow.transfer.integration.account.InvalidAccountResponseException
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 700ms
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
  retry:
    instances:
      accountService:
        max-attempts: 3
        wait-duration: 200ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - com.multimatics.bankflow.transfer.integration.account.AccountServiceTimeoutException
          - com.multimatics.bankflow.transfer.integration.account.AccountServiceUnavailableException
        ignore-exceptions:
          - com.multimatics.bankflow.transfer.integration.account.RemoteAccountNotFoundException
          - com.multimatics.bankflow.transfer.integration.account.InvalidAccountResponseException
bankflow:
  clients:
    account:
      connect-timeout: ${ACCOUNT_CONNECT_TIMEOUT:2s}
      read-timeout: ${ACCOUNT_READ_TIMEOUT:3s}
      lab-delay-ms: ${ACCOUNT_CLIENT_DELAY_MS:0}
  kafka:
    topics:
      transfer-completed: bankflow.transfer.completed.v1
